apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-binding
  namespace: tekton
spec:
  params:
    - name: revision
      value: $(body.pull_request.head.sha)
  triggerTemplate:
    name: github-pr-pipeline-template