apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-pr-pipeline-template
  namespace: tekton
spec:
  params:
    - name: revision
      description: The git revision (SHA)
      default: master
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: clone-build-push-run
      spec:
        pipelineRef:
          name: clone-build-push
        workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: docker-credentials
          secret:
            secretName: docker-credentials
        params:
        - name: revision
          value: $(tt.params.revision)
        
        # resources:
        #   - name: source
        #     resourceSpec:
        #       type: git
        #       params:
        #         - name: revision
        #           value: $(tt.params.revision)
